[package]
name = "adbx_runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "adbx_runtime"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
adbx_shared = { path = "../adbx_shared" }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rmp-serde = { workspace = true }